yorikvanhavre/BIM_Workbench

utils/buildPsets.py
Legacy __print__ statements are syntax errors in Python 3 but __print()__ function works as expected in both Python 2 and Python 3.
flake8 testing of https://github.com/yorikvanhavre/BIM_Workbench on Python 3.7.1
$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./BimSetup.py:194:63: F821 undefined name 'Vector'
FreeCAD.DraftWorkingPlane.alignToPointAndAxis(Vector(0,0,0), Vector(0,0,1), 0)
^
./BimSetup.py:194:78: F821 undefined name 'Vector'
FreeCAD.DraftWorkingPlane.alignToPointAndAxis(Vector(0,0,0), Vector(0,0,1), 0)
^
./BimSetup.py:197:63: F821 undefined name 'Vector'
FreeCAD.DraftWorkingPlane.alignToPointAndAxis(Vector(0,0,0), Vector(0,1,0), 0)
^
./BimSetup.py:197:78: F821 undefined name 'Vector' …
```
=> Use print() function in both Python 2 and Python 3

utils/getIfcElements.py
This utility allows us to check that the list of `IfcProduct` being supported in FreeCAD is always correct and up-to-date. The XSD can be gotten from here:
http://www.buildingsmart-tech.org/ifc/IFC4/Add2/html/annex/annex-a.htm
=> Add util to return a list of non-abstract children of IfcProduct

BimBox.py, BimLibrary.py
The tracker code is moved from the original `DraftTrackers` to a new module `draftguitools/gui_trackers`, with FreeCAD/FreeCAD#3092.
When that is merged, the code in BIM needs to be updated accordingly.
Forum thread: [[Discussion] Splitting Draft tools into their own modules](https://forum.freecadweb.org/viewtopic.php?f=23&t=38593&start=40#p370895).
=> BIM: import from new trackers module in Draft

InitGui.py
This name was changed from `Draft_SetWorkingPlaneProxy`, as it creates a new object; it doesn't really set one.
This has to be merged after the main pull request FreeCAD/FreeCAD#3094 is merged.
=> BIM: use new name of Draft tool, Draft_WorkingPlaneProxy

BimIfcExplorer.py
Hi Yorik,
a straigt forward change, that makes big IFC files much easier to navigate:
Add the name of building parts to treeview.
=> Show the object's name in IfcExplorer

BimIfcExplorer.py
The wrong exception was handled. Causing an exception every time an
object was selected in tree view. Also the properties list always stayed
empty.
=> IfcExplorer: fix exception handling

BimViews.py
An error occurs when selecting the Level/Proxy in BIM Views Manager
```
File "/mnt/home/.FreeCAD/Mod/BIM/BimViews.py", line 170, in select
FreeCADGui.Selection.clearSelection()
NameError: name 'FreeCADGui' is not defined
```
=> Fix name 'FreeCADGui' is not defined

BimViews.py
An error occurs when double clicking the Level/Proxy in the BIM Views manager
```
Traceback (most recent call last):
File "/mnt/home/.FreeCAD/Mod/BIM/BimViews.py", line 299, in show
NameError: name 'sys' is not defined
```
=> Fix error name 'sys' is not defined

BimSetup.py
`Vector` is not defined, so use the fully qualified name, `FreeCAD.Vector`.
Reported in the forum: [[ Bug ] BIM_Setup: Vector not defined.](https://forum.freecadweb.org/viewtopic.php?f=23&p=418628#p418628)
=> BIM: add proper FreeCAD Vector

BimLayers.py
Import the `Draft` module globally to have access to `Draft.makeLayer`, which internally calls `Draft.make_layer`.
Reported in the forum:
* [Using Layers, "Draft" is not defined](https://forum.freecadweb.org/viewtopic.php?f=23&t=48933)
* [New Layer -> NameError: name 'Draft' is not defined](https://forum.freecadweb.org/viewtopic.php?f=23&t=49666)
When this is merged, it will uncover an error with the legacy function `Draft.makeLayer`. This is corrected in a separate pull request made for the Draft Workbench, FreeCAD/FreeCAD#3732.
=> BIM: import Draft globally to have access to Draft.make_layer

InitGui.py
The error reads
```
module 'FreeCADGui' has no attribute 'listCommands'
```
This error is caused by a recent change in the main FreeCAD code, https://github.com/FreeCAD/FreeCAD/commit/9b529bc45c28e06434d371ba3cfef60de283a4dc.
The quick solution is to do this:
```py
if not hasattr(Gui, "listCommands"):
Gui.listCommands = Gui.Command.listAll
```
Then BIM will work with versions before that commit, and for future versions that have the new method `Command.listAll`.
=> BIM: add fix for removal of listCommands in the main FreeCAD code

BimSetup.py
Misspelling of `DefaultShapeLineWidth` means that the parameter is not read correctly and thus the setup has no effect.
[[ Bug ] BIM_Setup: LineWidth not handled properly](https://forum.freecadweb.org/viewtopic.php?f=23&t=48911#p435973)
=> BIM: fix misspelling of DefaultShapeLineWidth

BimClassification.py, BimIfcElements.py
Menu *Manage > Manage IFC Elements ...* gives this error when sketches are in the model:
19:52:21  Running the Python command 'BIM_IfcElements' failed:
Traceback (most recent call last):
File "/home/vince/.FreeCAD/Mod/BIM/BimIfcElements.py", line 66, in Activated
self.objectslist[obj.Name] = [obj.IfcRole,mat]
'Sketcher.SketchObject' object has no attribute 'IfcRole'
and then, after changing:
```python
if hasattr(obj,"Material") and obj.Material:
mat = obj.Material.Name
self.objectslist[obj.Name] = [obj.IfcRole,mat]
```
with:
```python
if hasattr(obj,"Material"):
try:
mat = obj.Material.Name
except AttributeError:
mat=""
if hasattr(obj,"IfcType"):
self.objectslist[obj.Name] = [obj.IfcType,mat]
elif hasattr(obj,"IfcRole"):
self.objectslist[obj.Name] = [obj.IfcRole,mat]    
```
another error …
=> handle 'Sketcher.SketchObject' object has no attribute 'IfcRole'

BimWrappedTools.py
QFileDialog.getOpenFileName returns a tuple which has as first element the selected file name, so we need to check this instead of just the tuple (which is always generated).
=> Avoid failure when cancelling image load

dialogProject.ui
Latitude and latitude should be provided in the [-90, +90] and [-180, +180] ranges.
Also, minimum value property must be set to be able to use negative numbers.
=> Use correct ranges for latitude and longitude in project setup

BimProject.py
Strings with accents must be passed as unicode strings to Draft.makeText so accented chars are correctly displayed in the building outline label.
=> Correctly display unicode strings in building outline label (building name in project setup) when using Python 2

package.xml
The actual name of the class in InitGui.py is BIMWorkbench.
=> Correct classname for icon location

BimStatusBar.py, InitGui.py
Two BIM widgets were still available in the toolbar area context menu after switching to a different workbench.
=> BIM: clean up toolbar area context menu on WB deactivation

InitGui.py
The Draft_Array command is obsolete and has been replaced by Draft_OrthoArray.
=> BIM: use Draft_OrthoArray instead of Draft_Array.

BimProjectManager.py
WPProxy objects belonging to levels were one levelHeight above their level.
=> BimProjectManager fix WPProxy Z coordinate

archobjects/archview.py, archobjects/base.py, archviewproviders/view_archview.py, archviewproviders/view_base.py
Using 2 arguments for addExtension is deprecated. A warning to that effect is displayed in the current version.
```
OS: Windows 8 build 9600
Word size of FreeCAD: 64-bit
Version: 0.21.0.33458 (Git)
Build type: Release
Branch: master
Hash: 8b89dd29d2382c72d738c52e8974216130ffa9db
Python 3.10.12, Qt 5.15.8, Coin 4.0.0, Vtk 9.1.0, OCC 7.6.3
Locale: Dutch/Netherlands (nl_NL)
Installed mods:
```
=> Bim: using 2 arguments for addExtension is deprecated

BimBox.py
The box dimensions were multiplied if the decimal separator was a comma. The factor would depend on the number of displayed units.
Note that because values are re-read from the inputboxes there is an accuracy issue. The number of displayed units will result in rounded values. This PR does not fix that.
=> BimBox: Fix multiplication of dimensions

InitGui.py
V0.21 has been released some time ago. We can therefore switch to a 'normal' snap toolbar for the BIM WB as well.
=> BIM: switch to normal snap toolbar

BimPreflight.py
After installing a pre-compiled package of IFCOpenShell-python (according to the documentation available at [freecad.org](https://wiki.freecad.org/IfcOpenShell#Using_a_pre-compiled_IfcOpenShell_package)), I was able to do a IFC pre-flight checks.
However I get an error because the version returned by `ifcopenshell.version` does not have a standard format (x.y.z).
It is in fact appended with the git commit id to read something like this `v0.7.0-f0e03c79d'`.
This PR uses the standard python version package to read the version and in case something a git commit is detected it will try to remove it.
Here are the information about my system:
```
OS: Ubuntu Core 20 (GNOME)
Word size of FreeCAD: 64-bit
Version: 0.21.1.33668 +26 (Git) Snap 759
Build type: Release
Branch: tag: 0.21.1
Hash: …
```
=> Update BimPreflight.py to allow prebuild version of ifcopenshell

BimSetup.py
```
OS: Ubuntu Core 20 (ubuntu:GNOME/ubuntu)
Word size of FreeCAD: 64-bit
Version: 0.21.2.33771 (Git) Snap 908
Build type: Release
Branch: tag: 0.21.2
Hash: b9bfa5c5507506e4515816414cd27f4851d00489
Python 3.8.10, Qt 5.15.7, Coin 4.0.0, Vtk 7.1.1, OCC 7.6.3
Locale: English/United Kingdom (en_GB)
Installed mods: 
* BIM 2021.12.0
```
```
20:02:31  Loading list of latest IfcOpenBot builds from https://github.com/IfcOpenBot/IfcOpenShell...
20:02:31  Traceback (most recent call last):
20:02:31    File "/home/jonathan/snap/freecad/common/Mod/BIM/./BimSetup.py", line 636, in handleLink
20:02:31      getIfcOpenShell()
20:02:31    File "/home/jonathan/snap/freecad/common/Mod/BIM/./BimSetup.py", line 691, in getIfcOpenShell
20:02:31      u = urllib.request.urlopen(url1)
20:02:32  NameError: name …
```
=> fix request calls in getIfcOpenShell

BimViews.py, dialogViews.ui
To enhance the usability and intuitiveness of the BIM View Manager, I propose adding the following features:
Firstly, I believe that when designing buildings, people generally spend more time considering the height of each floor rather than its level.
so I want to add a new "Height" field in the BIM View Manager to display the height of each floor.
Also enable direct editing of the height values within the BIM View Manager interface as well.
1. When modifying the height of a specific floor, recalculate the levels(.Placement.Base.z) of all floors above it.
2. When adjusting the level(.Placement.Base.z) of a floor, only recalculate the height for the edited floor and the one directly below it.
---
Adding floor heights in the BIM View Manager offers additional benefits. Before, changing the …
=> Update BIM View Manager

BimStructure.py
we could select multi  shapes to create walls, beams and columns at same time, but we couldn't do this  when making slabs.
we can make slab only by select each shape one by one.
not sure its a bug or design it on purpose
this PR fix making slabs from multi selections
hope not breaking anything
=> fix make slabs from multi selections

icons/Arch_Project_IFC.svg, icons/BIM_IfcElements.svg, icons/BIM_IfcProperties.svg, icons/BIM_IfcQuantities.svg, icons/BIM_Phases.svg, icons/IFC.svg
Update icons for better legibility on dark themes and current openBIM logo.
Tweaked colors to be consistent.
If you need different icons changed for the merge, also Arch/Draft, just let me know.
BIM logo currently is the only one pixelated:
=> Update icons for better legibility on dark themes

icons/Arch_Project_IFC.svg, icons/BIM_Classification.svg, icons/BIM_IfcElements.svg, icons/BIM_IfcProperties.svg, icons/BIM_IfcQuantities.svg, icons/BIM_Layers.svg, icons/BIM_Material.svg, icons/BIM_Phases.svg, icons/BIM_Preflight.svg, icons/BIM_Slab.svg, icons/BIM_Windows.svg, icons/Part_document.svg
Following @maxwxyz tweaks, make some more icons 64px based and use a consistent outline.
Also fix some issue with Slab icon.
=> Further tweaks to BIM WB icons
